# Generated by Django 5.1.1 on 2024-11-22 09:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_started',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
