# Generated by Django 5.1.1 on 2024-11-27 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembership',
            name='role',
            field=models.CharField(choices=[('MEMBER', 'Member'), ('MANAGER', 'Manager'), ('HEAD', 'Head')], default='Member', max_length=50),
        ),
    ]
