# Generated by Django 5.1.2 on 2024-11-19 15:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_project_id_teammembership_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('knowledge', 'Knowledge Base'), ('guides', 'Guides & eBooks'), ('webinars', 'Webinars & Videos'), ('templates', 'Templates & Tools'), ('community', 'Community Forum')], max_length=20)),
                ('file', models.FileField(upload_to='resources/')),
                ('uploaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('featured', models.BooleanField(default=False)),
            ],
        ),
    ]
