# Generated by Django 5.1.1 on 2024-11-22 09:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_date_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_started',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
