# Generated by Django 5.1.1 on 2024-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_task_date_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isAccepted',
            field=models.BooleanField(default=False),
        ),
    ]
