# Generated by Django 5.1.1 on 2024-12-01 06:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_user_date_of_hire_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isLogout',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='logoutTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
