# Generated by Django 5.1.1 on 2024-12-04 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_user_islogout_user_logouttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='res',
        ),
        migrations.RemoveField(
            model_name='file',
            name='user',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
        migrations.RemoveField(
            model_name='resources',
            name='user',
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.DeleteModel(
            name='Resources',
        ),
    ]
